OPENAI_API_KEY='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'

LANGCHAIN_TRACING_V2=true
LANGCHAIN_ENDPOINT="https://api.smith.langchain.com"
LANGCHAIN_API_KEY="ls__088e6dfd962940d184bfe8c9c1cad189"
LANGCHAIN_PROJECT="pandasAI"